owner: UK-DNS-Privacy-Project
repo: status
runner: "[self-hosted, linux, x64]"
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 1 1 *"
assignees:
  - 721p
sites:
  # Public WWW
  - name: website
    url: https://dnsprivacy.org.uk/
  
  # Authorative DNS Servers
  - name: ns1.dnsprivacy.org.uk
    check: "tcp-ping"
    url: ns1.dnsprivacy.org.uk
    port: 53
  - name: ns2.dnsprivacy.org.uk
    check: "tcp-ping"
    url: ns2.dnsprivacy.org.uk
    port: 53

  # Recursive DNS Servers
  - name: resolver-1.dnsprivacy.org.uk (DNS)
    check: "tcp-ping"
    url: resolver-1.dnsprivacy.org.uk
    port: 53
  - name: resolver-1.dnsprivacy.org.uk (DoH)
    url: https://resolver-1.dnsprivacy.org.uk/dns-query?dns=AAABAAABAAAAAAABCW5sbmV0bGFicwJubAAAHAABAAApEAAAAIAAAAA
    headers:
      - "Accept: application/dns-message"
    expectedStatusCodes:
      - 200
  - name: resolver-1.dnsprivacy.org.uk (DoT)
    check: "tcp-ping"
    url: resolver-1.dnsprivacy.org.uk
    port: 853
  - name: resolver-2.dnsprivacy.org.uk (DNS)
    check: "tcp-ping"
    url: resolver-2.dnsprivacy.org.uk
    port: 53
  - name: resolver-2.dnsprivacy.org.uk (DoH)
    url: https://resolver-2.dnsprivacy.org.uk/dns-query?dns=AAABAAABAAAAAAABCW5sbmV0bGFicwJubAAAHAABAAApEAAAAIAAAAA
    headers:
      - "Accept: application/dns-message"
    expectedStatusCodes:
      - 200
  - name: resolver-2.dnsprivacy.org.uk (DoT)
    check: "tcp-ping"
    url: resolver-2.dnsprivacy.org.uk
    port: 853

# Resolver Entrypoint
  - name: resolver.dnsprivacy.org.uk (DNS)
    check: "tcp-ping"
    url: resolver.dnsprivacy.org.uk
    port: 53
  - name: resolver.dnsprivacy.org.uk (DoH)
    url: https://resolver.dnsprivacy.org.uk/dns-query?dns=AAABAAABAAAAAAABCW5sbmV0bGFicwJubAAAHAABAAApEAAAAIAAAAA
    headers:
      - "Accept: application/dns-message"
    expectedStatusCodes:
      - 200
  - name: resolver.dnsprivacy.org.uk (DoT)
    check: "tcp-ping"
    url: resolver.dnsprivacy.org.uk
    port: 853

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/UK-DNS-Privacy-Project/status/refs/heads/master/assets/logo.png
  name: UK DNS Privacy Project
  introTitle: "UK DNS Privacy Project Service Status"
  introMessage: Welcome to the dnsprivacy.org.uk status page. Here you can monitor the uptime and availability of our privacy-first DNS services. We are committed to providing a reliable and secure experience, and this page ensures complete transparency about our service performance.
  navbar:
    - title: Home
      href: https://dnsprivacy.org.uk/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
